export const genericTemplate = {
  key: "generic",
  label: "Generic clerkship POMR",
  departments: [
    "General",
    "GI",
    "Endocrinology",
    "Rheumatology",
    "ID",
    "Surgery",
    "Pediatrics",
    "OB/GYN",
    "Cardiology",
    "Pulmonology",
    "Nephrology",
  ],
  admissionSections: [
    ["cc", "Chief complaint (CC) / 주호소"],
    ["hpi", "History of present illness (HPI) / 현병력"],
    ["pmh", "Past medical history (PMH) / 과거력"],
    ["psh", "Past surgical history (PSH) / 수술력"],
    ["medication", "Medication / 복용약"],
    ["allergy", "Allergy / 알레르기"],
    ["familyHistory", "Family history (FHx) / 가족력"],
    ["socialHistory", "Social history (SHx) / 사회력"],
    ["alcoholHistory", "Alcohol history / 음주력 - 기간, 주종, 주량"],
    ["smokingHistory", "Smoking history / 흡연력 - 기간, 양, pack-year"],
    ["ros", "Review of systems (ROS) / 계통문진"],
    ["physicalExam", "Physical examination (PE) / 신체진찰"],
    ["imageProcedureText", "Image/procedure text findings / 영상·시술 소견"],
  ],
} as const;
