export const genericTemplate = {
  key: "generic",
  label: "Generic clerkship POMR",
  departments: [
    "General",
    "Gastroenterology",
    "Endocrinology",
    "Rheumatology",
    "Infectious Diseases",
    "Surgery",
    "Pediatrics",
    "Obstetrics and Gynecology",
    "Cardiology",
    "Pulmonology",
    "Nephrology",
  ],
  admissionSections: [
    ["cc", "주호소 / Chief complaint"],
    ["hpi", "현병력 / History of present illness"],
    ["pmh", "과거력 / Past medical history"],
    ["psh", "수술력 / Past surgical history"],
    ["medication", "복용약 / Medication"],
    ["allergy", "알레르기 / Allergy"],
    ["familyHistory", "가족력 / Family history"],
    ["socialHistory", "사회력 / Social history"],
    ["alcoholHistory", "음주력 / Alcohol history - 기간, 주종, 주량"],
    ["smokingHistory", "흡연력 / Smoking history - 기간, 양, pack-year"],
    ["ros", "계통문진 / Review of systems"],
    ["physicalExam", "신체진찰 / Physical examination"],
    ["imageProcedureText", "영상·시술 소견 / Image and procedure text findings"],
  ],
} as const;
