export const genericTemplate = {
  key: "generic",
  label: "Generic clerkship POMR",
  departments: [
    "General",
    "GI",
    "Endocrinology",
    "Rheumatology",
    "ID",
    "Surgery",
    "Pediatrics",
    "OB/GYN",
    "Cardiology",
    "Pulmonology",
    "Nephrology",
  ],
  admissionSections: [
    ["cc", "CC"],
    ["hpi", "HPI"],
    ["pmh", "PMH"],
    ["psh", "PSH"],
    ["medication", "Medication"],
    ["allergy", "Allergy"],
    ["familyHistory", "Family history"],
    ["socialHistory", "Social history"],
    ["ros", "ROS"],
    ["physicalExam", "Physical examination"],
    ["imageProcedureText", "Image/procedure text findings"],
  ],
} as const;
